# Generated by Django 5.1.7 on 2025-03-21 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="content",
            field=models.TextField(verbose_name="Содержание"),
        ),
    ]
