# Generated by Django 5.1.7 on 2025-03-22 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_alter_blog_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="count_watches",
            field=models.IntegerField(default=0, verbose_name="Число просмотров"),
        ),
    ]
