# Generated by Django 5.1.7 on 2025-03-13 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_alter_category_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="photos/", verbose_name="изображение"
            ),
        ),
    ]
